### ISSUE TITLE
Installation glitch

### ISSUE THREAD

**Issue by ktavabi** [denysdovhan/dotfiles#26]
I am not sure what any of this is...

> error: failed to install source `https://github.com/spaceship-prompt/spaceship-prompt@4.x`
>   due to: failed to find branch `4.x`
>   due to: cannot locate remote-tracking branch 'origin/4.x'; class=Reference (4); code=NotFound (-3)
> (eval):alias:170: bad option: +x
> (eval):alias:178: bad option: -=

But this `repo` is turning into a can of worms! Not for me, thanks.

**Comment by Bearbobs** [comment]
same issue
@denysdovhan can you please look into
alias issue is from fig
not sure abt spaceship tried changing it to master but lot of promt issues

**Comment by denysdovhan** [comment]
The issue was with the missing spaceship 4.x branch. Should be resolved in the latest commits.

**Comment by ktavabi** [comment]
[This line](https://github.com/denysdovhan/dotfiles/blob/985d6e8d7aff62a99c444e2ec13d6652cb0ce553/scripts/sheldon#L18) in the sheldon script is still failing...

> info: latest release: 0.6.6
> error: current target aarch64-apple-darwin is not available for download
> Command [./scripts/sheldon] failed
